version: "3.8"

services:
  upf:
    container_name: upf
    image: free5gc/upf
    build:
      context: ./nf_upf
      args:
        DEBUG_TOOLS: "true"
    command: bash -c "./upf-iptables.sh && ./upf -c ./config/upfcfg.yaml"
    volumes:
      - ./config/upfcfg.yaml:/free5gc/config/upfcfg.yaml
      - ./config/upf-iptables.sh:/free5gc/upf-iptables.sh
    cap_add:
      - NET_ADMIN
    networks:
      free5gc:
        ipv4_address: 10.100.200.32
        aliases:
          - upf.srlabs.mobi

  db:
    container_name: mongodb
    image: mongo:4.4
    command: mongod --port 27017
    expose:
      - "27017"
    volumes:
      - free5gc:/data/db
    networks:
      free5gc:
        ipv4_address: 10.100.200.64
        aliases:
          - db

  nrf:
    container_name: nrf
    image: free5gc/nrf
    build:
      context: ./nf_nrf
      args:
        DEBUG_TOOLS: "true"
    command: ./nrf -c ./config/nrfcfg.yaml
    expose:
      - "8000"
    volumes:
      - ./config/nrfcfg.yaml:/free5gc/config/nrfcfg.yaml
      - ./cert:/free5gc/cert
    environment:
      DB_URI: mongodb://db/free5gc
      GIN_MODE: release
    networks:
      free5gc:
        ipv4_address: 10.100.200.16
        aliases:
          - nrf.srlabs.mobi
    depends_on:
      - db

  amf:
    container_name: amf
    image: free5gc/amf
    build:
      context: ./nf_amf
      args:
        DEBUG_TOOLS: "true"
    command: ./amf -c ./config/amfcfg.yaml
    expose:
      - "8000"
    volumes:
      - ./config/amfcfg.yaml:/free5gc/config/amfcfg.yaml
      - ./cert:/free5gc/cert
    environment:
      GIN_MODE: release
    networks:
      free5gc:
        ipv4_address: 10.100.200.35
        aliases:
          - amf.srlabs.mobi
    depends_on:
      - nrf

  ausf:
    container_name: ausf
    image: free5gc/ausf
    build:
      context: ./nf_ausf
      args:
        DEBUG_TOOLS: "true"
    command: ./ausf -c ./config/ausfcfg.yaml
    expose:
      - "8000"
    volumes:
      - ./config/ausfcfg.yaml:/free5gc/config/ausfcfg.yaml
      - ./cert:/free5gc/cert
    environment:
      GIN_MODE: release
    networks:
      free5gc:
        ipv4_address: 10.100.200.36
        aliases:
          - ausf.srlabs.mobi
    depends_on:
      - nrf

  nssf:
    container_name: nssf
    image: free5gc/nssf
    build:
      context: ./nf_nssf
      args:
        DEBUG_TOOLS: "true"
    command: ./nssf -c ./config/nssfcfg.yaml
    expose:
      - "8000"
    volumes:
      - ./config/nssfcfg.yaml:/free5gc/config/nssfcfg.yaml
      - ./cert:/free5gc/cert
    environment:
      GIN_MODE: release
    networks:
      free5gc:
        ipv4_address: 10.100.200.37
        aliases:
          - nssf.srlabs.mobi
    depends_on:
      - nrf

  pcf:
    container_name: pcf
    image: free5gc/pcf
    build:
      context: ./nf_pcf
      args:
        DEBUG_TOOLS: "true"
    command: ./pcf -c ./config/pcfcfg.yaml
    expose:
      - "8000"
    volumes:
      - ./config/pcfcfg.yaml:/free5gc/config/pcfcfg.yaml
      - ./cert:/free5gc/cert
    environment:
      GIN_MODE: release
    networks:
      free5gc:
        ipv4_address: 10.100.200.38
        aliases:
          - pcf.srlabs.mobi
    depends_on:
      - nrf

  smf:
    container_name: smf
    image: free5gc/smf
    build:
      context: ./nf_smf
      args:
        DEBUG_TOOLS: "true"
    command: ./smf -c ./config/smfcfg.yaml -u ./config/uerouting.yaml
    expose:
      - "8000"
    volumes:
      - ./config/smfcfg.yaml:/free5gc/config/smfcfg.yaml
      - ./config/uerouting.yaml:/free5gc/config/uerouting.yaml
      - ./cert:/free5gc/cert
    environment:
      GIN_MODE: release
    networks:
      free5gc:
        ipv4_address: 10.100.200.39
        aliases:
          - smf.srlabs.mobi
    depends_on:
      - nrf
      - upf

  udm:
    container_name: udm
    image: free5gc/udm
    build:
      context: ./nf_udm
      args:
        DEBUG_TOOLS: "true"
    command: ./udm -c ./config/udmcfg.yaml
    expose:
      - "8000"
    volumes:
      - ./config/udmcfg.yaml:/free5gc/config/udmcfg.yaml
      - ./cert:/free5gc/cert
    environment:
      GIN_MODE: release
    networks:
      free5gc:
        ipv4_address: 10.100.200.40
        aliases:
          - udm.srlabs.mobi
    depends_on:
      - db
      - nrf

  udr:
    container_name: udr
    image: free5gc/udr
    build:
      context: ./nf_udr
      args:
        DEBUG_TOOLS: "true"
    command: ./udr -c ./config/udrcfg.yaml
    expose:
      - "8000"
    volumes:
      - ./config/udrcfg.yaml:/free5gc/config/udrcfg.yaml
      - ./cert:/free5gc/cert
    environment:
      DB_URI: mongodb://db/free5gc
      GIN_MODE: release
    networks:
      free5gc:
        ipv4_address: 10.100.200.41
        aliases:
          - udr.srlabs.mobi
    depends_on:
      - db
      - nrf

  chf:
    container_name: chf
    image: free5gc/chf
    build:
      context: ./nf_chf
      args:
        DEBUG_TOOLS: "true"
    command: ./chf -c ./config/chfcfg.yaml
    expose:
      - "8000"
      - "2122"
    volumes:
      - ./config/chfcfg.yaml:/free5gc/config/chfcfg.yaml
      - ./cert:/free5gc/cert
    environment:
      DB_URI: mongodb://db/free5gc
      GIN_MODE: release
    networks:
      free5gc:
        ipv4_address: 10.100.200.42
        aliases:
          - chf.srlabs.mobi
    depends_on:
      - db
      - nrf
      - webui

  n3iwf:
    container_name: n3iwf
    image: free5gc/n3iwf
    build:
      context: ./nf_n3iwf
      args:
        DEBUG_TOOLS: "true"
    command: ./n3iwf -c ./config/n3iwfcfg.yaml
    volumes:
      - ./config/n3iwfcfg.yaml:/free5gc/config/n3iwfcfg.yaml
      - ./config/n3iwf-ipsec.sh:/free5gc/n3iwf-ipsec.sh
    environment:
      GIN_MODE: release
    cap_add:
      - NET_ADMIN
    networks:
      free5gc:
        ipv4_address: 10.100.200.43
        aliases:
          - n3iwf.srlabs.mobi
    depends_on:
      - amf
      - smf
      - upf

  tngf:
    container_name: tngf
    image: free5gc/tngf
    build:
      context: ./nf_tngf
      args:
        DEBUG_TOOLS: "true"
    command: ./tngf -c ./config/tngfcfg.yaml
    volumes:
      - ./config/tngfcfg.yaml:/free5gc/config/tngfcfg.yaml
      - ./cert:/free5gc/cert
    environment:
      GIN_MODE: release
    cap_add:
      - NET_ADMIN
    network_mode: host
    depends_on:
      - amf
      - smf
      - upf

  nef:
    container_name: nef
    image: free5gc/nef
    build:
      context: ./nf_nef
      args:
        DEBUG_TOOLS: "true"
    command: ./nef -c ./config/nefcfg.yaml
    expose:
      - "8000"
    volumes: 
      - ./config/nefcfg.yaml:/free5gc/config/nefcfg.yaml
      - ./cert:/free5gc/cert
    environment:
      GIN_MODE: release
    networks:
      free5gc:
        ipv4_address: 10.100.200.44
        aliases:
          - nef.srlabs.mobi
    depends_on:
      - db
      - nrf

  webui:
    container_name: webui
    image: free5gc/webui
    build:
      context: ./webui
      args:
        DEBUG_TOOLS: "true"
    command: ./webui -c ./config/webuicfg.yaml
    expose:
      - "2121"
    volumes:
      - ./config/webuicfg.yaml:/free5gc/config/webuicfg.yaml
    environment:
      - GIN_MODE=release
    networks:
      free5gc:
        ipv4_address: 10.100.200.65
        aliases:
          - webui.srlabs.mobi
    ports:
      - "5000:5000"
    depends_on:
      - db
      - nrf

  ueransim:
    container_name: ueransim
    image: free5gc/ueransim
    build:
      context: ./ueransim
    command: ./nr-gnb -c ./config/gnbcfg.yaml
    volumes:
      - ./config/gnbcfg.yaml:/ueransim/config/gnbcfg.yaml
      - ./config/uecfg.yaml:/ueransim/config/uecfg.yaml
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net/tun"
    networks:
      free5gc:
        ipv4_address: 10.100.200.254
        aliases:
          - gnb.srlabs.mobi
    depends_on:
      - amf
      - upf

  n3iwue:
    container_name: n3iwue
    image: free5gc/n3iwue
    build:
      context: ./n3iwue
    command: bash -c "ip route del default && ip route add default via 10.100.200.1 dev eth0 metric 203 && sleep infinity"
    volumes:
      - ./config/n3uecfg.yaml:/n3iwue/config/n3ue.yaml
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net/tun"
    networks:
      free5gc:
        ipv4_address: 10.100.200.253
        aliases:
          - n3ue.srlabs.mobi
    depends_on:
      - n3iwf
      
      
networks:
  free5gc:
    ipam:
      driver: default
      config:
        - subnet: 10.100.200.0/24
    driver_opts:
      com.docker.network.bridge.name: br-free5gc

volumes:
  free5gc:
