version: "3.8"

services:
  upf:
    container_name: upf
    image: free5gc/upf
    command: bash -c "./upf-iptables.sh && ./upf -c ./config/upfcfg.yaml"
    volumes:
      - ./config/upfcfg.yaml:/free5gc/config/upfcfg.yaml
      - ./config/upf-iptables.sh:/free5gc/upf-iptables.sh
    cap_add:
      - NET_ADMIN
    networks:
      corenet:
        ipv4_address: 10.0.0.159
        aliases:
          - upf.srlabs.mobi

  db:
    container_name: mongodb
    image: mongo:4.4
    command: mongod --port 27017
    ports:
      - "27017"
    volumes:
      - free5gc:/data/db
    networks:
      corenet:
        ipv4_address: 10.0.0.112
        aliases:
          - db

  nrf:
    container_name: nrf
    image: free5gc/nrf
    command: ./nrf -c ./config/nrfcfg.yaml
    ports:
      - "8000"
    volumes:
      - ./config/nrfcfg.yaml:/free5gc/config/nrfcfg.yaml
      - ./cert:/free5gc/cert
    environment:
      DB_URI: mongodb://db/free5gc
      GIN_MODE: release
    networks:
      corenet:
        ipv4_address: 10.0.0.150
        aliases:
          - nrf.srlabs.mobi
    depends_on:
      - db

  amf:
    container_name: amf
    image: free5gc/amf
    command: ./amf -c ./config/amfcfg.yaml
    ports:
      - "8000"
    volumes:
      - ./config/amfcfg.yaml:/free5gc/config/amfcfg.yaml
      - ./cert:/free5gc/cert
    environment:
      GIN_MODE: release
    networks:
      corenet:
        ipv4_address: 10.0.0.151
        aliases:
          - amf.srlabs.mobi
    depends_on:
      - nrf

  ausf:
    container_name: ausf
    image: free5gc/ausf
    command: ./ausf -c ./config/ausfcfg.yaml
    ports:
      - "8000"
    volumes:
      - ./config/ausfcfg.yaml:/free5gc/config/ausfcfg.yaml
      - ./cert:/free5gc/cert
    environment:
      GIN_MODE: release
    networks:
      corenet:
        ipv4_address: 10.0.0.155
        aliases:
          - ausf.srlabs.mobi
    depends_on:
      - nrf

  nssf:
    container_name: nssf
    image: free5gc/nssf
    command: ./nssf -c ./config/nssfcfg.yaml
    ports:
      - "8000"
    volumes:
      - ./config/nssfcfg.yaml:/free5gc/config/nssfcfg.yaml
      - ./cert:/free5gc/cert
    environment:
      GIN_MODE: release
    networks:
      corenet:
        ipv4_address: 10.0.0.158
        aliases:
          - nssf.srlabs.mobi
    depends_on:
      - nrf

  pcf:
    container_name: pcf
    image: free5gc/pcf
    command: ./pcf -c ./config/pcfcfg.yaml
    ports:
      - "8000"
    volumes:
      - ./config/pcfcfg.yaml:/free5gc/config/pcfcfg.yaml
      - ./cert:/free5gc/cert
    environment:
      GIN_MODE: release
    networks:
      corenet:
        ipv4_address: 10.0.0.157
        aliases:
          - pcf.srlabs.mobi
    depends_on:
      - nrf

  smf:
    container_name: smf
    image: free5gc/smf
    command: ./smf -c ./config/smfcfg.yaml -u ./config/uerouting.yaml
    ports:
      - "8000"
    volumes:
      - ./config/smfcfg.yaml:/free5gc/config/smfcfg.yaml
      - ./config/uerouting.yaml:/free5gc/config/uerouting.yaml
      - ./cert:/free5gc/cert
    environment:
      GIN_MODE: release
    networks:
      corenet:
        ipv4_address: 10.0.0.152
        aliases:
          - smf.srlabs.mobi
    depends_on:
      - nrf
      - upf

  udm:
    container_name: udm
    image: free5gc/udm
    command: ./udm -c ./config/udmcfg.yaml
    ports:
      - "8000"
    volumes:
      - ./config/udmcfg.yaml:/free5gc/config/udmcfg.yaml
      - ./cert:/free5gc/cert
    environment:
      GIN_MODE: release
    networks:
      corenet:
        ipv4_address: 10.0.0.154
        aliases:
          - udm.srlabs.mobi
    depends_on:
      - db
      - nrf

  udr:
    container_name: udr
    image: free5gc/udr
    command: ./udr -c ./config/udrcfg.yaml
    ports:
      - "8000"
    volumes:
      - ./config/udrcfg.yaml:/free5gc/config/udrcfg.yaml
      - ./cert:/free5gc/cert
    environment:
      DB_URI: mongodb://db/free5gc
      GIN_MODE: release
    networks:
      corenet:
        ipv4_address: 10.0.0.153
        aliases:
          - udr.srlabs.mobi
    depends_on:
      - db
      - nrf

  chf:
    container_name: chf
    image: free5gc/chf
    command: ./chf -c ./config/chfcfg.yaml
    ports:
      - "8000"
      - "2122"
    volumes:
      - ./config/chfcfg.yaml:/free5gc/config/chfcfg.yaml
      - ./cert:/free5gc/cert
    environment:
      DB_URI: mongodb://db/free5gc
      GIN_MODE: release
    networks:
      corenet:
        ipv4_address: 10.0.0.170
        aliases:
          - chf.srlabs.mobi
    depends_on:
      - db
      - nrf
      - webui

  n3iwf:
    container_name: n3iwf
    image: free5gc/n3iwf
    command: ./n3iwf -c ./config/n3iwfcfg.yaml
    volumes:
      - ./config/n3iwfcfg.yaml:/free5gc/config/n3iwfcfg.yaml
      - ./config/n3iwf-ipsec.sh:/free5gc/n3iwf-ipsec.sh
    environment:
      GIN_MODE: release
    cap_add:
      - NET_ADMIN
    networks:
      corenet:
        ipv4_address: 10.0.0.
        aliases:
          - n3iwf.srlabs.mobi
    depends_on:
      - amf
      - smf
      - upf

  tngf:
    container_name: tngf
    image: free5gc/tngf
    command: ./tngf -c ./config/tngfcfg.yaml
    volumes:
      - ./config/tngfcfg.yaml:/free5gc/config/tngfcfg.yaml
      - ./cert:/free5gc/cert
    environment:
      GIN_MODE: release
    cap_add:
      - NET_ADMIN
    network_mode: host
    depends_on:
      - amf
      - smf
      - upf

  nef:
    container_name: nef
    image: free5gc/nef
    command: ./nef -c ./config/nefcfg.yaml
    ports:
      - "8000"
    volumes: 
      - ./config/nefcfg.yaml:/free5gc/config/nefcfg.yaml
      - ./cert:/free5gc/cert
    environment:
      GIN_MODE: release
    networks:
      corenet:
        ipv4_address: 10.0.0.171
        aliases:
          - nef.srlabs.mobi
    depends_on:
      - db
      - nrf

  webui:
    container_name: webui
    image: free5gc/webui
    command: ./webui -c ./config/webuicfg.yaml
    expose:
      - "2121"
    volumes:
      - ./config/webuicfg.yaml:/free5gc/config/webuicfg.yaml
    environment:
      - GIN_MODE=release
    networks:
      corenet:
        ipv4_address: 10.0.0.183
        aliases:
          - webui.srlabs.mobi
    ports:
      - "5000:5000"
    depends_on:
      - db
      - nrf

  ueransim:
    container_name: ueransim
    image: free5gc/ueransim
    command: ./nr-gnb -c ./config/gnbcfg.yaml
    volumes:
      - ./config/gnbcfg.yaml:/ueransim/config/gnbcfg.yaml
      - ./config/uecfg.yaml:/ueransim/config/uecfg.yaml
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net/tun"
    networks:
      corenet:
        ipv4_address: 10.0.0.254
        aliases:
          - gnb.srlabs.mobi
    depends_on:
      - amf
      - upf

  n3iwue:
    container_name: n3iwue
    image: free5gc/n3iwue
    command: bash -c "ip route del default && ip route add default via 10.0.0.1 dev eth0 metric 203 && sleep infinity"
    volumes:
      - ./config/n3uecfg.yaml:/n3iwue/config/n3ue.yaml
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net/tun"
    networks:
      corenet:
        ipv4_address: 10.0.0.253
        aliases:
          - n3ue.srlabs.mobi
    depends_on:
      - n3iwf

networks:
  corenet:
    external: true

volumes:
  free5gc:
