global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
      - targets: ["amf.srlabs.mobi:9091"]
      - targets: ["ausf.srlabs.mobi:9091"]
      - targets: ["chf.srlabs.mobi:9091"]
      - targets: ["n3iwf.srlabs.mobi:9091"]
      - targets: ["nrf.srlabs.mobi:9091"]
      - targets: ["nssf.srlabs.mobi:9091"]
      - targets: ["pcf.srlabs.mobi:9091"]
      - targets: ["smf.srlabs.mobi:9091"]
      - targets: ["tngf.srlabs.mobi:9091"]
      - targets: ["udm.srlabs.mobi:9091"]
      - targets: ["udr.srlabs.mobi:9091"]
